package com.playtranslate.language

import android.content.Context
import java.io.FileNotFoundException
import java.util.concurrent.ConcurrentHashMap

/**
 * Per-language phrase fuse-exclusion lists for [LatinEngine.tokenize]'s
 * re-glob, loaded once from `assets/phrase_nofuse/<code>.txt` (generated by
 * `scripts/gen_phrase_nofuse.py` plus the LLM-adjudicated block). Entries
 * are locale-lowercased phrase forms that must never FUSE — sequences the
 * data can't distinguish from real expressions but that are usually
 * compositional in ordinary text ("do you", "i know"). Lookup is
 * deliberately unaffected: a typed query still resolves these entries; only
 * the tokenizer stops swallowing their member words.
 *
 * A missing asset means no exclusions for that language — the empty set is
 * cached so absent files cost one probe per process.
 */
object PhraseNofuse {

    private val cache = ConcurrentHashMap<String, Set<String>>()

    fun forLang(context: Context, langId: SourceLangId): Set<String> =
        cache.getOrPut(langId.code) {
            try {
                context.assets.open("phrase_nofuse/${langId.code}.txt")
                    .bufferedReader()
                    .useLines { lines ->
                        lines.map { it.trim() }
                            .filter { it.isNotEmpty() && !it.startsWith("#") }
                            .toSet()
                    }
            } catch (_: FileNotFoundException) {
                emptySet()
            }
        }
}
