/*
 * Copyright (C) 2024-2026  Yomitan Authors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

// Generated by scripts/gen_japanese_transforms.mjs from yomidevs/yomitan ext/js/language/ja/japanese-transforms.js at 833409247c5e30a976551a6475843b3a4896ef2f; do not edit by hand.

package com.playtranslate.dictionary.deinflect

import com.playtranslate.dictionary.deinflect.Rule.Suffix
import com.playtranslate.dictionary.deinflect.Rule.WholeWord

/**
 * Yomitan's Japanese deinflection table as data: 22 conditions and
 * 55 transforms holding 894 rules (886 suffix, 8 whole-word), in
 * upstream order. The table's helper spreads are expanded in place, so a
 * rule's position in its transform's list is its upstream rule index.
 */
internal object JapaneseTransforms {
    const val UPSTREAM_COMMIT = "833409247c5e30a976551a6475843b3a4896ef2f"

    val descriptor: TransformDescriptor = TransformDescriptor(
        conditions = conditions(),
        transforms = listOf(
            transform00(),
            transform01(),
            transform02(),
            transform03(),
            transform04(),
            transform05(),
            transform06(),
            transform07(),
            transform08(),
            transform09(),
            transform10(),
            transform11(),
            transform12(),
            transform13(),
            transform14(),
            transform15(),
            transform16(),
            transform17(),
            transform18(),
            transform19(),
            transform20(),
            transform21(),
            transform22(),
            transform23(),
            transform24(),
            transform25(),
            transform26(),
            transform27(),
            transform28(),
            transform29(),
            transform30(),
            transform31(),
            transform32(),
            transform33(),
            transform34(),
            transform35(),
            transform36(),
            transform37(),
            transform38(),
            transform39(),
            transform40(),
            transform41(),
            transform42(),
            transform43(),
            transform44(),
            transform45(),
            transform46(),
            transform47(),
            transform48(),
            transform49(),
            transform50(),
            transform51(),
            transform52(),
            transform53(),
            transform54(),
        ),
    )

    private fun conditions(): List<Condition> = listOf(
        Condition("v", isDictionaryForm = false, subConditions = listOf("v1", "v5", "vk", "vs", "vz")), // Verb
        Condition("v1", isDictionaryForm = true, subConditions = listOf("v1d", "v1p")), // Ichidan verb
        Condition("v1d", isDictionaryForm = false, subConditions = null), // Ichidan verb, dictionary form
        Condition("v1p", isDictionaryForm = false, subConditions = null), // Ichidan verb, progressive or perfect form
        Condition("v5", isDictionaryForm = true, subConditions = listOf("v5d", "v5s")), // Godan verb
        Condition("v5d", isDictionaryForm = false, subConditions = null), // Godan verb, dictionary form
        Condition("v5s", isDictionaryForm = false, subConditions = listOf("v5ss", "v5sp")), // Godan verb, short causative form
        Condition("v5ss", isDictionaryForm = false, subConditions = null), // Godan verb, short causative form having さす ending (cannot conjugate with passive form)
        Condition("v5sp", isDictionaryForm = false, subConditions = null), // Godan verb, short causative form not having さす ending (can conjugate with passive form)
        Condition("vk", isDictionaryForm = true, subConditions = null), // Kuru verb
        Condition("vs", isDictionaryForm = true, subConditions = null), // Suru verb
        Condition("vz", isDictionaryForm = true, subConditions = null), // Zuru verb
        Condition("adj-i", isDictionaryForm = true, subConditions = null), // Adjective with i ending
        Condition("-ます", isDictionaryForm = false, subConditions = null), // Polite -ます ending
        Condition("-ません", isDictionaryForm = false, subConditions = null), // Polite negative -ません ending
        Condition("-て", isDictionaryForm = false, subConditions = null), // Intermediate -て endings for progressive or perfect tense
        Condition("-ば", isDictionaryForm = false, subConditions = null), // Intermediate -ば endings for conditional contraction
        Condition("-く", isDictionaryForm = false, subConditions = null), // Intermediate -く endings for adverbs
        Condition("-た", isDictionaryForm = false, subConditions = null), // -た form ending
        Condition("-ん", isDictionaryForm = false, subConditions = null), // -ん negative ending
        Condition("-なさい", isDictionaryForm = false, subConditions = null), // Intermediate -なさい ending (polite imperative)
        Condition("-ゃ", isDictionaryForm = false, subConditions = null), // Intermediate -や ending (conditional contraction)
    )

    private fun transform00(): Transform = Transform(
        key = "-ば",
        name = "-ば",
        rules = listOf(
            Suffix("ければ", "い", listOf("-ば"), listOf("adj-i")),
            Suffix("えば", "う", listOf("-ば"), listOf("v5")),
            Suffix("へば", "う", listOf("-ば"), listOf("v5")),
            Suffix("けば", "く", listOf("-ば"), listOf("v5")),
            Suffix("げば", "ぐ", listOf("-ば"), listOf("v5")),
            Suffix("せば", "す", listOf("-ば"), listOf("v5")),
            Suffix("てば", "つ", listOf("-ば"), listOf("v5")),
            Suffix("ねば", "ぬ", listOf("-ば"), listOf("v5")),
            Suffix("べば", "ぶ", listOf("-ば"), listOf("v5")),
            Suffix("めば", "む", listOf("-ば"), listOf("v5")),
            Suffix("れば", "る", listOf("-ば"), listOf("v1", "v5", "vk", "vs", "vz")),
            Suffix("れば", "", listOf("-ば"), listOf("-ます")),
        ),
    )

    private fun transform01(): Transform = Transform(
        key = "-ゃ",
        name = "-ゃ",
        rules = listOf(
            Suffix("けりゃ", "ければ", listOf("-ゃ"), listOf("-ば")),
            Suffix("きゃ", "ければ", listOf("-ゃ"), listOf("-ば")),
            Suffix("や", "えば", listOf("-ゃ"), listOf("-ば")),
            Suffix("きゃ", "けば", listOf("-ゃ"), listOf("-ば")),
            Suffix("ぎゃ", "げば", listOf("-ゃ"), listOf("-ば")),
            Suffix("しゃ", "せば", listOf("-ゃ"), listOf("-ば")),
            Suffix("ちゃ", "てば", listOf("-ゃ"), listOf("-ば")),
            Suffix("にゃ", "ねば", listOf("-ゃ"), listOf("-ば")),
            Suffix("びゃ", "べば", listOf("-ゃ"), listOf("-ば")),
            Suffix("みゃ", "めば", listOf("-ゃ"), listOf("-ば")),
            Suffix("りゃ", "れば", listOf("-ゃ"), listOf("-ば")),
        ),
    )

    private fun transform02(): Transform = Transform(
        key = "-ちゃ",
        name = "-ちゃ",
        rules = listOf(
            Suffix("ちゃ", "る", listOf("v5"), listOf("v1")),
            Suffix("いじゃ", "ぐ", listOf("v5"), listOf("v5")),
            Suffix("いちゃ", "く", listOf("v5"), listOf("v5")),
            Suffix("しちゃ", "す", listOf("v5"), listOf("v5")),
            Suffix("っちゃ", "う", listOf("v5"), listOf("v5")),
            Suffix("っちゃ", "く", listOf("v5"), listOf("v5")),
            Suffix("っちゃ", "つ", listOf("v5"), listOf("v5")),
            Suffix("っちゃ", "る", listOf("v5"), listOf("v5")),
            Suffix("んじゃ", "ぬ", listOf("v5"), listOf("v5")),
            Suffix("んじゃ", "ぶ", listOf("v5"), listOf("v5")),
            Suffix("んじゃ", "む", listOf("v5"), listOf("v5")),
            Suffix("じちゃ", "ずる", listOf("v5"), listOf("vz")),
            Suffix("しちゃ", "する", listOf("v5"), listOf("vs")),
            Suffix("為ちゃ", "為る", listOf("v5"), listOf("vs")),
            Suffix("きちゃ", "くる", listOf("v5"), listOf("vk")),
            Suffix("来ちゃ", "来る", listOf("v5"), listOf("vk")),
            Suffix("來ちゃ", "來る", listOf("v5"), listOf("vk")),
        ),
    )

    private fun transform03(): Transform = Transform(
        key = "-ちゃう",
        name = "-ちゃう",
        rules = listOf(
            Suffix("ちゃう", "る", listOf("v5"), listOf("v1")),
            Suffix("いじゃう", "ぐ", listOf("v5"), listOf("v5")),
            Suffix("いちゃう", "く", listOf("v5"), listOf("v5")),
            Suffix("しちゃう", "す", listOf("v5"), listOf("v5")),
            Suffix("っちゃう", "う", listOf("v5"), listOf("v5")),
            Suffix("っちゃう", "く", listOf("v5"), listOf("v5")),
            Suffix("っちゃう", "つ", listOf("v5"), listOf("v5")),
            Suffix("っちゃう", "る", listOf("v5"), listOf("v5")),
            Suffix("んじゃう", "ぬ", listOf("v5"), listOf("v5")),
            Suffix("んじゃう", "ぶ", listOf("v5"), listOf("v5")),
            Suffix("んじゃう", "む", listOf("v5"), listOf("v5")),
            Suffix("じちゃう", "ずる", listOf("v5"), listOf("vz")),
            Suffix("しちゃう", "する", listOf("v5"), listOf("vs")),
            Suffix("為ちゃう", "為る", listOf("v5"), listOf("vs")),
            Suffix("きちゃう", "くる", listOf("v5"), listOf("vk")),
            Suffix("来ちゃう", "来る", listOf("v5"), listOf("vk")),
            Suffix("來ちゃう", "來る", listOf("v5"), listOf("vk")),
        ),
    )

    private fun transform04(): Transform = Transform(
        key = "-ちまう",
        name = "-ちまう",
        rules = listOf(
            Suffix("ちまう", "る", listOf("v5"), listOf("v1")),
            Suffix("いじまう", "ぐ", listOf("v5"), listOf("v5")),
            Suffix("いちまう", "く", listOf("v5"), listOf("v5")),
            Suffix("しちまう", "す", listOf("v5"), listOf("v5")),
            Suffix("っちまう", "う", listOf("v5"), listOf("v5")),
            Suffix("っちまう", "く", listOf("v5"), listOf("v5")),
            Suffix("っちまう", "つ", listOf("v5"), listOf("v5")),
            Suffix("っちまう", "る", listOf("v5"), listOf("v5")),
            Suffix("んじまう", "ぬ", listOf("v5"), listOf("v5")),
            Suffix("んじまう", "ぶ", listOf("v5"), listOf("v5")),
            Suffix("んじまう", "む", listOf("v5"), listOf("v5")),
            Suffix("じちまう", "ずる", listOf("v5"), listOf("vz")),
            Suffix("しちまう", "する", listOf("v5"), listOf("vs")),
            Suffix("為ちまう", "為る", listOf("v5"), listOf("vs")),
            Suffix("きちまう", "くる", listOf("v5"), listOf("vk")),
            Suffix("来ちまう", "来る", listOf("v5"), listOf("vk")),
            Suffix("來ちまう", "來る", listOf("v5"), listOf("vk")),
        ),
    )

    private fun transform05(): Transform = Transform(
        key = "-しまう",
        name = "-しまう",
        rules = listOf(
            Suffix("てしまう", "て", listOf("v5"), listOf("-て")),
            Suffix("でしまう", "で", listOf("v5"), listOf("-て")),
        ),
    )

    private fun transform06(): Transform = Transform(
        key = "-なさい",
        name = "-なさい",
        rules = listOf(
            Suffix("なさい", "る", listOf("-なさい"), listOf("v1")),
            Suffix("いなさい", "う", listOf("-なさい"), listOf("v5")),
            Suffix("ひなさい", "う", listOf("-なさい"), listOf("v5")),
            Suffix("きなさい", "く", listOf("-なさい"), listOf("v5")),
            Suffix("ぎなさい", "ぐ", listOf("-なさい"), listOf("v5")),
            Suffix("しなさい", "す", listOf("-なさい"), listOf("v5")),
            Suffix("ちなさい", "つ", listOf("-なさい"), listOf("v5")),
            Suffix("になさい", "ぬ", listOf("-なさい"), listOf("v5")),
            Suffix("びなさい", "ぶ", listOf("-なさい"), listOf("v5")),
            Suffix("みなさい", "む", listOf("-なさい"), listOf("v5")),
            Suffix("りなさい", "る", listOf("-なさい"), listOf("v5")),
            Suffix("じなさい", "ずる", listOf("-なさい"), listOf("vz")),
            Suffix("しなさい", "する", listOf("-なさい"), listOf("vs")),
            Suffix("為なさい", "為る", listOf("-なさい"), listOf("vs")),
            Suffix("きなさい", "くる", listOf("-なさい"), listOf("vk")),
            Suffix("来なさい", "来る", listOf("-なさい"), listOf("vk")),
            Suffix("來なさい", "來る", listOf("-なさい"), listOf("vk")),
        ),
    )

    private fun transform07(): Transform = Transform(
        key = "-そう",
        name = "-そう",
        rules = listOf(
            Suffix("そう", "い", emptyList(), listOf("adj-i")),
            Suffix("さう", "い", emptyList(), listOf("adj-i")),
            Suffix("そう", "る", emptyList(), listOf("v1")),
            Suffix("さう", "る", emptyList(), listOf("v1")),
            Suffix("いそう", "う", emptyList(), listOf("v5")),
            Suffix("ひさう", "う", emptyList(), listOf("v5")),
            Suffix("きそう", "く", emptyList(), listOf("v5")),
            Suffix("きさう", "く", emptyList(), listOf("v5")),
            Suffix("ぎそう", "ぐ", emptyList(), listOf("v5")),
            Suffix("ぎさう", "ぐ", emptyList(), listOf("v5")),
            Suffix("しそう", "す", emptyList(), listOf("v5")),
            Suffix("しさう", "す", emptyList(), listOf("v5")),
            Suffix("ちそう", "つ", emptyList(), listOf("v5")),
            Suffix("ちさう", "つ", emptyList(), listOf("v5")),
            Suffix("にそう", "ぬ", emptyList(), listOf("v5")),
            Suffix("にさう", "ぬ", emptyList(), listOf("v5")),
            Suffix("びそう", "ぶ", emptyList(), listOf("v5")),
            Suffix("びさう", "ぶ", emptyList(), listOf("v5")),
            Suffix("みそう", "む", emptyList(), listOf("v5")),
            Suffix("みさう", "む", emptyList(), listOf("v5")),
            Suffix("りそう", "る", emptyList(), listOf("v5")),
            Suffix("りさう", "る", emptyList(), listOf("v5")),
            Suffix("じそう", "ずる", emptyList(), listOf("vz")),
            Suffix("じさう", "ずる", emptyList(), listOf("vz")),
            Suffix("しそう", "する", emptyList(), listOf("vs")),
            Suffix("しさう", "する", emptyList(), listOf("vs")),
            Suffix("為そう", "為る", emptyList(), listOf("vs")),
            Suffix("為さう", "為る", emptyList(), listOf("vs")),
            Suffix("きそう", "くる", emptyList(), listOf("vk")),
            Suffix("きさう", "くる", emptyList(), listOf("vk")),
            Suffix("来そう", "来る", emptyList(), listOf("vk")),
            Suffix("来さう", "来る", emptyList(), listOf("vk")),
            Suffix("來そう", "來る", emptyList(), listOf("vk")),
            Suffix("來さう", "來る", emptyList(), listOf("vk")),
        ),
    )

    private fun transform08(): Transform = Transform(
        key = "-すぎる",
        name = "-すぎる",
        rules = listOf(
            Suffix("すぎる", "い", listOf("v1"), listOf("adj-i")),
            Suffix("すぎる", "る", listOf("v1"), listOf("v1")),
            Suffix("いすぎる", "う", listOf("v1"), listOf("v5")),
            Suffix("ひすぎる", "う", listOf("v1"), listOf("v5")),
            Suffix("きすぎる", "く", listOf("v1"), listOf("v5")),
            Suffix("ぎすぎる", "ぐ", listOf("v1"), listOf("v5")),
            Suffix("しすぎる", "す", listOf("v1"), listOf("v5")),
            Suffix("ちすぎる", "つ", listOf("v1"), listOf("v5")),
            Suffix("にすぎる", "ぬ", listOf("v1"), listOf("v5")),
            Suffix("びすぎる", "ぶ", listOf("v1"), listOf("v5")),
            Suffix("みすぎる", "む", listOf("v1"), listOf("v5")),
            Suffix("りすぎる", "る", listOf("v1"), listOf("v5")),
            Suffix("じすぎる", "ずる", listOf("v1"), listOf("vz")),
            Suffix("しすぎる", "する", listOf("v1"), listOf("vs")),
            Suffix("為すぎる", "為る", listOf("v1"), listOf("vs")),
            Suffix("きすぎる", "くる", listOf("v1"), listOf("vk")),
            Suffix("来すぎる", "来る", listOf("v1"), listOf("vk")),
            Suffix("來すぎる", "來る", listOf("v1"), listOf("vk")),
        ),
    )

    private fun transform09(): Transform = Transform(
        key = "-過ぎる",
        name = "-過ぎる",
        rules = listOf(
            Suffix("過ぎる", "い", listOf("v1"), listOf("adj-i")),
            Suffix("過ぎる", "る", listOf("v1"), listOf("v1")),
            Suffix("い過ぎる", "う", listOf("v1"), listOf("v5")),
            Suffix("ひ過ぎる", "う", listOf("v1"), listOf("v5")),
            Suffix("き過ぎる", "く", listOf("v1"), listOf("v5")),
            Suffix("ぎ過ぎる", "ぐ", listOf("v1"), listOf("v5")),
            Suffix("し過ぎる", "す", listOf("v1"), listOf("v5")),
            Suffix("ち過ぎる", "つ", listOf("v1"), listOf("v5")),
            Suffix("に過ぎる", "ぬ", listOf("v1"), listOf("v5")),
            Suffix("び過ぎる", "ぶ", listOf("v1"), listOf("v5")),
            Suffix("み過ぎる", "む", listOf("v1"), listOf("v5")),
            Suffix("り過ぎる", "る", listOf("v1"), listOf("v5")),
            Suffix("じ過ぎる", "ずる", listOf("v1"), listOf("vz")),
            Suffix("し過ぎる", "する", listOf("v1"), listOf("vs")),
            Suffix("為過ぎる", "為る", listOf("v1"), listOf("vs")),
            Suffix("き過ぎる", "くる", listOf("v1"), listOf("vk")),
            Suffix("来過ぎる", "来る", listOf("v1"), listOf("vk")),
            Suffix("來過ぎる", "來る", listOf("v1"), listOf("vk")),
        ),
    )

    private fun transform10(): Transform = Transform(
        key = "-たい",
        name = "-たい",
        rules = listOf(
            Suffix("たい", "る", listOf("adj-i"), listOf("v1")),
            Suffix("いたい", "う", listOf("adj-i"), listOf("v5")),
            Suffix("ひたい", "う", listOf("adj-i"), listOf("v5")),
            Suffix("きたい", "く", listOf("adj-i"), listOf("v5")),
            Suffix("ぎたい", "ぐ", listOf("adj-i"), listOf("v5")),
            Suffix("したい", "す", listOf("adj-i"), listOf("v5")),
            Suffix("ちたい", "つ", listOf("adj-i"), listOf("v5")),
            Suffix("にたい", "ぬ", listOf("adj-i"), listOf("v5")),
            Suffix("びたい", "ぶ", listOf("adj-i"), listOf("v5")),
            Suffix("みたい", "む", listOf("adj-i"), listOf("v5")),
            Suffix("りたい", "る", listOf("adj-i"), listOf("v5")),
            Suffix("じたい", "ずる", listOf("adj-i"), listOf("vz")),
            Suffix("したい", "する", listOf("adj-i"), listOf("vs")),
            Suffix("為たい", "為る", listOf("adj-i"), listOf("vs")),
            Suffix("きたい", "くる", listOf("adj-i"), listOf("vk")),
            Suffix("来たい", "来る", listOf("adj-i"), listOf("vk")),
            Suffix("來たい", "來る", listOf("adj-i"), listOf("vk")),
        ),
    )

    private fun transform11(): Transform = Transform(
        key = "-たら",
        name = "-たら",
        rules = listOf(
            Suffix("かったら", "い", emptyList(), listOf("adj-i")),
            Suffix("たら", "る", emptyList(), listOf("v1")),
            Suffix("いたら", "く", emptyList(), listOf("v5")),
            Suffix("いだら", "ぐ", emptyList(), listOf("v5")),
            Suffix("したら", "す", emptyList(), listOf("v5")),
            Suffix("ったら", "う", emptyList(), listOf("v5")),
            Suffix("ったら", "つ", emptyList(), listOf("v5")),
            Suffix("ったら", "る", emptyList(), listOf("v5")),
            Suffix("んだら", "ぬ", emptyList(), listOf("v5")),
            Suffix("んだら", "ぶ", emptyList(), listOf("v5")),
            Suffix("んだら", "む", emptyList(), listOf("v5")),
            Suffix("じたら", "ずる", emptyList(), listOf("vz")),
            Suffix("したら", "する", emptyList(), listOf("vs")),
            Suffix("為たら", "為る", emptyList(), listOf("vs")),
            Suffix("きたら", "くる", emptyList(), listOf("vk")),
            Suffix("来たら", "来る", emptyList(), listOf("vk")),
            Suffix("來たら", "來る", emptyList(), listOf("vk")),
            // rules 17 to 35: ...irregularVerbSuffixInflections('たら', [], ['v5']), expanded
            Suffix("いったら", "いく", emptyList(), listOf("v5")),
            Suffix("行ったら", "行く", emptyList(), listOf("v5")),
            Suffix("逝ったら", "逝く", emptyList(), listOf("v5")),
            Suffix("往ったら", "往く", emptyList(), listOf("v5")),
            Suffix("こうたら", "こう", emptyList(), listOf("v5")),
            Suffix("とうたら", "とう", emptyList(), listOf("v5")),
            Suffix("請うたら", "請う", emptyList(), listOf("v5")),
            Suffix("乞うたら", "乞う", emptyList(), listOf("v5")),
            Suffix("恋うたら", "恋う", emptyList(), listOf("v5")),
            Suffix("問うたら", "問う", emptyList(), listOf("v5")),
            Suffix("訪うたら", "訪う", emptyList(), listOf("v5")),
            Suffix("宣うたら", "宣う", emptyList(), listOf("v5")),
            Suffix("曰うたら", "曰う", emptyList(), listOf("v5")),
            Suffix("給うたら", "給う", emptyList(), listOf("v5")),
            Suffix("賜うたら", "賜う", emptyList(), listOf("v5")),
            Suffix("揺蕩うたら", "揺蕩う", emptyList(), listOf("v5")),
            Suffix("のたもうたら", "のたまう", emptyList(), listOf("v5")),
            Suffix("たもうたら", "たまう", emptyList(), listOf("v5")),
            Suffix("たゆとうたら", "たゆたう", emptyList(), listOf("v5")),
            Suffix("ましたら", "ます", emptyList(), listOf("-ます")),
        ),
    )

    private fun transform12(): Transform = Transform(
        key = "-たり",
        name = "-たり",
        rules = listOf(
            Suffix("かったり", "い", emptyList(), listOf("adj-i")),
            Suffix("たり", "る", emptyList(), listOf("v1")),
            Suffix("いたり", "く", emptyList(), listOf("v5")),
            Suffix("いだり", "ぐ", emptyList(), listOf("v5")),
            Suffix("したり", "す", emptyList(), listOf("v5")),
            Suffix("ったり", "う", emptyList(), listOf("v5")),
            Suffix("ったり", "つ", emptyList(), listOf("v5")),
            Suffix("ったり", "る", emptyList(), listOf("v5")),
            Suffix("んだり", "ぬ", emptyList(), listOf("v5")),
            Suffix("んだり", "ぶ", emptyList(), listOf("v5")),
            Suffix("んだり", "む", emptyList(), listOf("v5")),
            Suffix("じたり", "ずる", emptyList(), listOf("vz")),
            Suffix("したり", "する", emptyList(), listOf("vs")),
            Suffix("為たり", "為る", emptyList(), listOf("vs")),
            Suffix("きたり", "くる", emptyList(), listOf("vk")),
            Suffix("来たり", "来る", emptyList(), listOf("vk")),
            Suffix("來たり", "來る", emptyList(), listOf("vk")),
            // rules 17 to 35: ...irregularVerbSuffixInflections('たり', [], ['v5']), expanded
            Suffix("いったり", "いく", emptyList(), listOf("v5")),
            Suffix("行ったり", "行く", emptyList(), listOf("v5")),
            Suffix("逝ったり", "逝く", emptyList(), listOf("v5")),
            Suffix("往ったり", "往く", emptyList(), listOf("v5")),
            Suffix("こうたり", "こう", emptyList(), listOf("v5")),
            Suffix("とうたり", "とう", emptyList(), listOf("v5")),
            Suffix("請うたり", "請う", emptyList(), listOf("v5")),
            Suffix("乞うたり", "乞う", emptyList(), listOf("v5")),
            Suffix("恋うたり", "恋う", emptyList(), listOf("v5")),
            Suffix("問うたり", "問う", emptyList(), listOf("v5")),
            Suffix("訪うたり", "訪う", emptyList(), listOf("v5")),
            Suffix("宣うたり", "宣う", emptyList(), listOf("v5")),
            Suffix("曰うたり", "曰う", emptyList(), listOf("v5")),
            Suffix("給うたり", "給う", emptyList(), listOf("v5")),
            Suffix("賜うたり", "賜う", emptyList(), listOf("v5")),
            Suffix("揺蕩うたり", "揺蕩う", emptyList(), listOf("v5")),
            Suffix("のたもうたり", "のたまう", emptyList(), listOf("v5")),
            Suffix("たもうたり", "たまう", emptyList(), listOf("v5")),
            Suffix("たゆとうたり", "たゆたう", emptyList(), listOf("v5")),
        ),
    )

    private fun transform13(): Transform = Transform(
        key = "-て",
        name = "-て",
        rules = listOf(
            Suffix("くて", "い", listOf("-て"), listOf("adj-i")),
            Suffix("て", "る", listOf("-て"), listOf("v1")),
            Suffix("いて", "く", listOf("-て"), listOf("v5")),
            Suffix("いで", "ぐ", listOf("-て"), listOf("v5")),
            Suffix("して", "す", listOf("-て"), listOf("v5")),
            Suffix("って", "う", listOf("-て"), listOf("v5")),
            Suffix("って", "つ", listOf("-て"), listOf("v5")),
            Suffix("って", "る", listOf("-て"), listOf("v5")),
            Suffix("んで", "ぬ", listOf("-て"), listOf("v5")),
            Suffix("んで", "ぶ", listOf("-て"), listOf("v5")),
            Suffix("んで", "む", listOf("-て"), listOf("v5")),
            Suffix("じて", "ずる", listOf("-て"), listOf("vz")),
            Suffix("して", "する", listOf("-て"), listOf("vs")),
            Suffix("為て", "為る", listOf("-て"), listOf("vs")),
            Suffix("きて", "くる", listOf("-て"), listOf("vk")),
            Suffix("来て", "来る", listOf("-て"), listOf("vk")),
            Suffix("來て", "來る", listOf("-て"), listOf("vk")),
            // rules 17 to 35: ...irregularVerbSuffixInflections('て', ['-て'], ['v5']), expanded
            Suffix("いって", "いく", listOf("-て"), listOf("v5")),
            Suffix("行って", "行く", listOf("-て"), listOf("v5")),
            Suffix("逝って", "逝く", listOf("-て"), listOf("v5")),
            Suffix("往って", "往く", listOf("-て"), listOf("v5")),
            Suffix("こうて", "こう", listOf("-て"), listOf("v5")),
            Suffix("とうて", "とう", listOf("-て"), listOf("v5")),
            Suffix("請うて", "請う", listOf("-て"), listOf("v5")),
            Suffix("乞うて", "乞う", listOf("-て"), listOf("v5")),
            Suffix("恋うて", "恋う", listOf("-て"), listOf("v5")),
            Suffix("問うて", "問う", listOf("-て"), listOf("v5")),
            Suffix("訪うて", "訪う", listOf("-て"), listOf("v5")),
            Suffix("宣うて", "宣う", listOf("-て"), listOf("v5")),
            Suffix("曰うて", "曰う", listOf("-て"), listOf("v5")),
            Suffix("給うて", "給う", listOf("-て"), listOf("v5")),
            Suffix("賜うて", "賜う", listOf("-て"), listOf("v5")),
            Suffix("揺蕩うて", "揺蕩う", listOf("-て"), listOf("v5")),
            Suffix("のたもうて", "のたまう", listOf("-て"), listOf("v5")),
            Suffix("たもうて", "たまう", listOf("-て"), listOf("v5")),
            Suffix("たゆとうて", "たゆたう", listOf("-て"), listOf("v5")),
            Suffix("まして", "ます", emptyList(), listOf("-ます")),
        ),
    )

    private fun transform14(): Transform = Transform(
        key = "-ず",
        name = "-ず",
        rules = listOf(
            Suffix("ず", "る", emptyList(), listOf("v1")),
            Suffix("かず", "く", emptyList(), listOf("v5")),
            Suffix("がず", "ぐ", emptyList(), listOf("v5")),
            Suffix("さず", "す", emptyList(), listOf("v5")),
            Suffix("たず", "つ", emptyList(), listOf("v5")),
            Suffix("なず", "ぬ", emptyList(), listOf("v5")),
            Suffix("ばず", "ぶ", emptyList(), listOf("v5")),
            Suffix("まず", "む", emptyList(), listOf("v5")),
            Suffix("らず", "る", emptyList(), listOf("v5")),
            Suffix("わず", "う", emptyList(), listOf("v5")),
            Suffix("はず", "う", emptyList(), listOf("v5")),
            Suffix("ぜず", "ずる", emptyList(), listOf("vz")),
            Suffix("せず", "する", emptyList(), listOf("vs")),
            Suffix("為ず", "為る", emptyList(), listOf("vs")),
            Suffix("こず", "くる", emptyList(), listOf("vk")),
            Suffix("来ず", "来る", emptyList(), listOf("vk")),
            Suffix("來ず", "來る", emptyList(), listOf("vk")),
        ),
    )

    private fun transform15(): Transform = Transform(
        key = "-ぬ",
        name = "-ぬ",
        rules = listOf(
            Suffix("ぬ", "る", emptyList(), listOf("v1")),
            Suffix("かぬ", "く", emptyList(), listOf("v5")),
            Suffix("がぬ", "ぐ", emptyList(), listOf("v5")),
            Suffix("さぬ", "す", emptyList(), listOf("v5")),
            Suffix("たぬ", "つ", emptyList(), listOf("v5")),
            Suffix("なぬ", "ぬ", emptyList(), listOf("v5")),
            Suffix("ばぬ", "ぶ", emptyList(), listOf("v5")),
            Suffix("まぬ", "む", emptyList(), listOf("v5")),
            Suffix("らぬ", "る", emptyList(), listOf("v5")),
            Suffix("わぬ", "う", emptyList(), listOf("v5")),
            Suffix("はぬ", "う", emptyList(), listOf("v5")),
            Suffix("ぜぬ", "ずる", emptyList(), listOf("vz")),
            Suffix("せぬ", "する", emptyList(), listOf("vs")),
            Suffix("為ぬ", "為る", emptyList(), listOf("vs")),
            Suffix("こぬ", "くる", emptyList(), listOf("vk")),
            Suffix("来ぬ", "来る", emptyList(), listOf("vk")),
            Suffix("來ぬ", "來る", emptyList(), listOf("vk")),
        ),
    )

    private fun transform16(): Transform = Transform(
        key = "-ん",
        name = "-ん",
        rules = listOf(
            Suffix("ん", "る", listOf("-ん"), listOf("v1")),
            Suffix("かん", "く", listOf("-ん"), listOf("v5")),
            Suffix("がん", "ぐ", listOf("-ん"), listOf("v5")),
            Suffix("さん", "す", listOf("-ん"), listOf("v5")),
            Suffix("たん", "つ", listOf("-ん"), listOf("v5")),
            Suffix("なん", "ぬ", listOf("-ん"), listOf("v5")),
            Suffix("ばん", "ぶ", listOf("-ん"), listOf("v5")),
            Suffix("まん", "む", listOf("-ん"), listOf("v5")),
            Suffix("らん", "る", listOf("-ん"), listOf("v5")),
            Suffix("わん", "う", listOf("-ん"), listOf("v5")),
            Suffix("はん", "う", listOf("-ん"), listOf("v5")),
            Suffix("ぜん", "ずる", listOf("-ん"), listOf("vz")),
            Suffix("せん", "する", listOf("-ん"), listOf("vs")),
            Suffix("為ん", "為る", listOf("-ん"), listOf("vs")),
            Suffix("こん", "くる", listOf("-ん"), listOf("vk")),
            Suffix("来ん", "来る", listOf("-ん"), listOf("vk")),
            Suffix("來ん", "來る", listOf("-ん"), listOf("vk")),
        ),
    )

    private fun transform17(): Transform = Transform(
        key = "-んばかり",
        name = "-んばかり",
        rules = listOf(
            Suffix("んばかり", "る", emptyList(), listOf("v1")),
            Suffix("かんばかり", "く", emptyList(), listOf("v5")),
            Suffix("がんばかり", "ぐ", emptyList(), listOf("v5")),
            Suffix("さんばかり", "す", emptyList(), listOf("v5")),
            Suffix("たんばかり", "つ", emptyList(), listOf("v5")),
            Suffix("なんばかり", "ぬ", emptyList(), listOf("v5")),
            Suffix("ばんばかり", "ぶ", emptyList(), listOf("v5")),
            Suffix("まんばかり", "む", emptyList(), listOf("v5")),
            Suffix("らんばかり", "る", emptyList(), listOf("v5")),
            Suffix("わんばかり", "う", emptyList(), listOf("v5")),
            Suffix("はんばかり", "う", emptyList(), listOf("v5")),
            Suffix("ぜんばかり", "ずる", emptyList(), listOf("vz")),
            Suffix("せんばかり", "する", emptyList(), listOf("vs")),
            Suffix("為んばかり", "為る", emptyList(), listOf("vs")),
            Suffix("こんばかり", "くる", emptyList(), listOf("vk")),
            Suffix("来んばかり", "来る", emptyList(), listOf("vk")),
            Suffix("來んばかり", "來る", emptyList(), listOf("vk")),
        ),
    )

    private fun transform18(): Transform = Transform(
        key = "-んとする",
        name = "-んとする",
        rules = listOf(
            Suffix("んとする", "る", listOf("vs"), listOf("v1")),
            Suffix("かんとする", "く", listOf("vs"), listOf("v5")),
            Suffix("がんとする", "ぐ", listOf("vs"), listOf("v5")),
            Suffix("さんとする", "す", listOf("vs"), listOf("v5")),
            Suffix("たんとする", "つ", listOf("vs"), listOf("v5")),
            Suffix("なんとする", "ぬ", listOf("vs"), listOf("v5")),
            Suffix("ばんとする", "ぶ", listOf("vs"), listOf("v5")),
            Suffix("まんとする", "む", listOf("vs"), listOf("v5")),
            Suffix("らんとする", "る", listOf("vs"), listOf("v5")),
            Suffix("わんとする", "う", listOf("vs"), listOf("v5")),
            Suffix("はんとする", "う", listOf("vs"), listOf("v5")),
            Suffix("ぜんとする", "ずる", listOf("vs"), listOf("vz")),
            Suffix("せんとする", "する", listOf("vs"), listOf("vs")),
            Suffix("為んとする", "為る", listOf("vs"), listOf("vs")),
            Suffix("こんとする", "くる", listOf("vs"), listOf("vk")),
            Suffix("来んとする", "来る", listOf("vs"), listOf("vk")),
            Suffix("來んとする", "來る", listOf("vs"), listOf("vk")),
        ),
    )

    private fun transform19(): Transform = Transform(
        key = "-む",
        name = "-む",
        rules = listOf(
            Suffix("む", "る", emptyList(), listOf("v1")),
            Suffix("かむ", "く", emptyList(), listOf("v5")),
            Suffix("がむ", "ぐ", emptyList(), listOf("v5")),
            Suffix("さむ", "す", emptyList(), listOf("v5")),
            Suffix("たむ", "つ", emptyList(), listOf("v5")),
            Suffix("なむ", "ぬ", emptyList(), listOf("v5")),
            Suffix("ばむ", "ぶ", emptyList(), listOf("v5")),
            Suffix("まむ", "む", emptyList(), listOf("v5")),
            Suffix("らむ", "る", emptyList(), listOf("v5")),
            Suffix("わむ", "う", emptyList(), listOf("v5")),
            Suffix("はむ", "う", emptyList(), listOf("v5")),
            Suffix("ぜむ", "ずる", emptyList(), listOf("vz")),
            Suffix("せむ", "する", emptyList(), listOf("vs")),
            Suffix("為む", "為る", emptyList(), listOf("vs")),
            Suffix("こむ", "くる", emptyList(), listOf("vk")),
            Suffix("来む", "来る", emptyList(), listOf("vk")),
            Suffix("來む", "來る", emptyList(), listOf("vk")),
        ),
    )

    private fun transform20(): Transform = Transform(
        key = "-ざる",
        name = "-ざる",
        rules = listOf(
            Suffix("ざる", "る", emptyList(), listOf("v1")),
            Suffix("かざる", "く", emptyList(), listOf("v5")),
            Suffix("がざる", "ぐ", emptyList(), listOf("v5")),
            Suffix("さざる", "す", emptyList(), listOf("v5")),
            Suffix("たざる", "つ", emptyList(), listOf("v5")),
            Suffix("なざる", "ぬ", emptyList(), listOf("v5")),
            Suffix("ばざる", "ぶ", emptyList(), listOf("v5")),
            Suffix("まざる", "む", emptyList(), listOf("v5")),
            Suffix("らざる", "る", emptyList(), listOf("v5")),
            Suffix("わざる", "う", emptyList(), listOf("v5")),
            Suffix("はざる", "う", emptyList(), listOf("v5")),
            Suffix("ぜざる", "ずる", emptyList(), listOf("vz")),
            Suffix("せざる", "する", emptyList(), listOf("vs")),
            Suffix("為ざる", "為る", emptyList(), listOf("vs")),
            Suffix("こざる", "くる", emptyList(), listOf("vk")),
            Suffix("来ざる", "来る", emptyList(), listOf("vk")),
            Suffix("來ざる", "來る", emptyList(), listOf("vk")),
        ),
    )

    private fun transform21(): Transform = Transform(
        key = "-ねば",
        name = "-ねば",
        rules = listOf(
            Suffix("ねば", "る", listOf("-ば"), listOf("v1")),
            Suffix("かねば", "く", listOf("-ば"), listOf("v5")),
            Suffix("がねば", "ぐ", listOf("-ば"), listOf("v5")),
            Suffix("さねば", "す", listOf("-ば"), listOf("v5")),
            Suffix("たねば", "つ", listOf("-ば"), listOf("v5")),
            Suffix("なねば", "ぬ", listOf("-ば"), listOf("v5")),
            Suffix("ばねば", "ぶ", listOf("-ば"), listOf("v5")),
            Suffix("まねば", "む", listOf("-ば"), listOf("v5")),
            Suffix("らねば", "る", listOf("-ば"), listOf("v5")),
            Suffix("わねば", "う", listOf("-ば"), listOf("v5")),
            Suffix("はねば", "う", listOf("-ば"), listOf("v5")),
            Suffix("ぜねば", "ずる", listOf("-ば"), listOf("vz")),
            Suffix("せねば", "する", listOf("-ば"), listOf("vs")),
            Suffix("為ねば", "為る", listOf("-ば"), listOf("vs")),
            Suffix("こねば", "くる", listOf("-ば"), listOf("vk")),
            Suffix("来ねば", "来る", listOf("-ば"), listOf("vk")),
            Suffix("來ねば", "來る", listOf("-ば"), listOf("vk")),
        ),
    )

    private fun transform22(): Transform = Transform(
        key = "-く",
        name = "-く",
        rules = listOf(
            Suffix("く", "い", listOf("-く"), listOf("adj-i")),
        ),
    )

    private fun transform23(): Transform = Transform(
        key = "causative",
        name = "causative",
        rules = listOf(
            Suffix("させる", "る", listOf("v1"), listOf("v1")),
            Suffix("かせる", "く", listOf("v1"), listOf("v5")),
            Suffix("がせる", "ぐ", listOf("v1"), listOf("v5")),
            Suffix("させる", "す", listOf("v1"), listOf("v5")),
            Suffix("たせる", "つ", listOf("v1"), listOf("v5")),
            Suffix("なせる", "ぬ", listOf("v1"), listOf("v5")),
            Suffix("ばせる", "ぶ", listOf("v1"), listOf("v5")),
            Suffix("ませる", "む", listOf("v1"), listOf("v5")),
            Suffix("らせる", "る", listOf("v1"), listOf("v5")),
            Suffix("わせる", "う", listOf("v1"), listOf("v5")),
            Suffix("はせる", "う", listOf("v1"), listOf("v5")),
            Suffix("じさせる", "ずる", listOf("v1"), listOf("vz")),
            Suffix("ぜさせる", "ずる", listOf("v1"), listOf("vz")),
            Suffix("させる", "する", listOf("v1"), listOf("vs")),
            Suffix("為せる", "為る", listOf("v1"), listOf("vs")),
            Suffix("せさせる", "する", listOf("v1"), listOf("vs")),
            Suffix("為させる", "為る", listOf("v1"), listOf("vs")),
            Suffix("こさせる", "くる", listOf("v1"), listOf("vk")),
            Suffix("来させる", "来る", listOf("v1"), listOf("vk")),
            Suffix("來させる", "來る", listOf("v1"), listOf("vk")),
        ),
    )

    private fun transform24(): Transform = Transform(
        key = "short causative",
        name = "short causative",
        rules = listOf(
            Suffix("さす", "る", listOf("v5ss"), listOf("v1")),
            Suffix("かす", "く", listOf("v5sp"), listOf("v5")),
            Suffix("がす", "ぐ", listOf("v5sp"), listOf("v5")),
            Suffix("さす", "す", listOf("v5ss"), listOf("v5")),
            Suffix("たす", "つ", listOf("v5sp"), listOf("v5")),
            Suffix("なす", "ぬ", listOf("v5sp"), listOf("v5")),
            Suffix("ばす", "ぶ", listOf("v5sp"), listOf("v5")),
            Suffix("ます", "む", listOf("v5sp"), listOf("v5")),
            Suffix("らす", "る", listOf("v5sp"), listOf("v5")),
            Suffix("わす", "う", listOf("v5sp"), listOf("v5")),
            Suffix("はす", "う", listOf("v5sp"), listOf("v5")),
            Suffix("じさす", "ずる", listOf("v5ss"), listOf("vz")),
            Suffix("ぜさす", "ずる", listOf("v5ss"), listOf("vz")),
            Suffix("さす", "する", listOf("v5ss"), listOf("vs")),
            Suffix("為す", "為る", listOf("v5ss"), listOf("vs")),
            Suffix("こさす", "くる", listOf("v5ss"), listOf("vk")),
            Suffix("来さす", "来る", listOf("v5ss"), listOf("vk")),
            Suffix("來さす", "來る", listOf("v5ss"), listOf("vk")),
        ),
    )

    private fun transform25(): Transform = Transform(
        key = "imperative",
        name = "imperative",
        rules = listOf(
            Suffix("ろ", "る", emptyList(), listOf("v1")),
            Suffix("よ", "る", emptyList(), listOf("v1")),
            Suffix("え", "う", emptyList(), listOf("v5")),
            Suffix("へ", "う", emptyList(), listOf("v5")),
            Suffix("け", "く", emptyList(), listOf("v5")),
            Suffix("げ", "ぐ", emptyList(), listOf("v5")),
            Suffix("せ", "す", emptyList(), listOf("v5")),
            Suffix("て", "つ", emptyList(), listOf("v5")),
            Suffix("ね", "ぬ", emptyList(), listOf("v5")),
            Suffix("べ", "ぶ", emptyList(), listOf("v5")),
            Suffix("め", "む", emptyList(), listOf("v5")),
            Suffix("れ", "る", emptyList(), listOf("v5")),
            Suffix("じろ", "ずる", emptyList(), listOf("vz")),
            Suffix("ぜよ", "ずる", emptyList(), listOf("vz")),
            Suffix("しろ", "する", emptyList(), listOf("vs")),
            Suffix("せよ", "する", emptyList(), listOf("vs")),
            Suffix("為ろ", "為る", emptyList(), listOf("vs")),
            Suffix("為よ", "為る", emptyList(), listOf("vs")),
            Suffix("こい", "くる", emptyList(), listOf("vk")),
            Suffix("来い", "来る", emptyList(), listOf("vk")),
            Suffix("來い", "來る", emptyList(), listOf("vk")),
        ),
    )

    private fun transform26(): Transform = Transform(
        key = "continuative",
        name = "continuative",
        rules = listOf(
            Suffix("い", "いる", emptyList(), listOf("v1d")),
            Suffix("え", "える", emptyList(), listOf("v1d")),
            Suffix("き", "きる", emptyList(), listOf("v1d")),
            Suffix("ぎ", "ぎる", emptyList(), listOf("v1d")),
            Suffix("け", "ける", emptyList(), listOf("v1d")),
            Suffix("げ", "げる", emptyList(), listOf("v1d")),
            Suffix("じ", "じる", emptyList(), listOf("v1d")),
            Suffix("せ", "せる", emptyList(), listOf("v1d")),
            Suffix("ぜ", "ぜる", emptyList(), listOf("v1d")),
            Suffix("ち", "ちる", emptyList(), listOf("v1d")),
            Suffix("て", "てる", emptyList(), listOf("v1d")),
            Suffix("で", "でる", emptyList(), listOf("v1d")),
            Suffix("に", "にる", emptyList(), listOf("v1d")),
            Suffix("ね", "ねる", emptyList(), listOf("v1d")),
            Suffix("ひ", "ひる", emptyList(), listOf("v1d")),
            Suffix("び", "びる", emptyList(), listOf("v1d")),
            Suffix("へ", "へる", emptyList(), listOf("v1d")),
            Suffix("べ", "べる", emptyList(), listOf("v1d")),
            Suffix("み", "みる", emptyList(), listOf("v1d")),
            Suffix("め", "める", emptyList(), listOf("v1d")),
            Suffix("り", "りる", emptyList(), listOf("v1d")),
            Suffix("れ", "れる", emptyList(), listOf("v1d")),
            Suffix("い", "う", emptyList(), listOf("v5")),
            Suffix("ひ", "う", emptyList(), listOf("v5")),
            Suffix("き", "く", emptyList(), listOf("v5")),
            Suffix("ぎ", "ぐ", emptyList(), listOf("v5")),
            Suffix("し", "す", emptyList(), listOf("v5")),
            Suffix("ち", "つ", emptyList(), listOf("v5")),
            Suffix("に", "ぬ", emptyList(), listOf("v5")),
            Suffix("び", "ぶ", emptyList(), listOf("v5")),
            Suffix("み", "む", emptyList(), listOf("v5")),
            Suffix("り", "る", emptyList(), listOf("v5")),
            Suffix("き", "くる", emptyList(), listOf("vk")),
            Suffix("し", "する", emptyList(), listOf("vs")),
            Suffix("来", "来る", emptyList(), listOf("vk")),
            Suffix("來", "來る", emptyList(), listOf("vk")),
        ),
    )

    private fun transform27(): Transform = Transform(
        key = "negative",
        name = "negative",
        rules = listOf(
            Suffix("くない", "い", listOf("adj-i"), listOf("adj-i")),
            Suffix("ない", "る", listOf("adj-i"), listOf("v1")),
            Suffix("かない", "く", listOf("adj-i"), listOf("v5")),
            Suffix("がない", "ぐ", listOf("adj-i"), listOf("v5")),
            Suffix("さない", "す", listOf("adj-i"), listOf("v5")),
            Suffix("たない", "つ", listOf("adj-i"), listOf("v5")),
            Suffix("なない", "ぬ", listOf("adj-i"), listOf("v5")),
            Suffix("ばない", "ぶ", listOf("adj-i"), listOf("v5")),
            Suffix("まない", "む", listOf("adj-i"), listOf("v5")),
            Suffix("らない", "る", listOf("adj-i"), listOf("v5")),
            Suffix("わない", "う", listOf("adj-i"), listOf("v5")),
            Suffix("はない", "う", listOf("adj-i"), listOf("v5")),
            Suffix("じない", "ずる", listOf("adj-i"), listOf("vz")),
            Suffix("しない", "する", listOf("adj-i"), listOf("vs")),
            Suffix("為ない", "為る", listOf("adj-i"), listOf("vs")),
            Suffix("こない", "くる", listOf("adj-i"), listOf("vk")),
            Suffix("来ない", "来る", listOf("adj-i"), listOf("vk")),
            Suffix("來ない", "來る", listOf("adj-i"), listOf("vk")),
            Suffix("ません", "ます", listOf("-ません"), listOf("-ます")),
        ),
    )

    private fun transform28(): Transform = Transform(
        key = "-さ",
        name = "-さ",
        rules = listOf(
            Suffix("さ", "い", emptyList(), listOf("adj-i")),
        ),
    )

    private fun transform29(): Transform = Transform(
        key = "passive",
        name = "passive",
        rules = listOf(
            Suffix("かれる", "く", listOf("v1"), listOf("v5")),
            Suffix("がれる", "ぐ", listOf("v1"), listOf("v5")),
            Suffix("される", "す", listOf("v1"), listOf("v5d", "v5sp")),
            Suffix("たれる", "つ", listOf("v1"), listOf("v5")),
            Suffix("なれる", "ぬ", listOf("v1"), listOf("v5")),
            Suffix("ばれる", "ぶ", listOf("v1"), listOf("v5")),
            Suffix("まれる", "む", listOf("v1"), listOf("v5")),
            Suffix("われる", "う", listOf("v1"), listOf("v5")),
            Suffix("はれる", "う", listOf("v1"), listOf("v5")),
            Suffix("られる", "る", listOf("v1"), listOf("v5")),
            Suffix("じされる", "ずる", listOf("v1"), listOf("vz")),
            Suffix("ぜされる", "ずる", listOf("v1"), listOf("vz")),
            Suffix("される", "する", listOf("v1"), listOf("vs")),
            Suffix("為れる", "為る", listOf("v1"), listOf("vs")),
            Suffix("こられる", "くる", listOf("v1"), listOf("vk")),
            Suffix("来られる", "来る", listOf("v1"), listOf("vk")),
            Suffix("來られる", "來る", listOf("v1"), listOf("vk")),
        ),
    )

    private fun transform30(): Transform = Transform(
        key = "-た",
        name = "-た",
        rules = listOf(
            Suffix("かった", "い", listOf("-た"), listOf("adj-i")),
            Suffix("た", "る", listOf("-た"), listOf("v1")),
            Suffix("いた", "く", listOf("-た"), listOf("v5")),
            Suffix("いだ", "ぐ", listOf("-た"), listOf("v5")),
            Suffix("した", "す", listOf("-た"), listOf("v5")),
            Suffix("った", "う", listOf("-た"), listOf("v5")),
            Suffix("った", "つ", listOf("-た"), listOf("v5")),
            Suffix("った", "る", listOf("-た"), listOf("v5")),
            Suffix("んだ", "ぬ", listOf("-た"), listOf("v5")),
            Suffix("んだ", "ぶ", listOf("-た"), listOf("v5")),
            Suffix("んだ", "む", listOf("-た"), listOf("v5")),
            Suffix("じた", "ずる", listOf("-た"), listOf("vz")),
            Suffix("した", "する", listOf("-た"), listOf("vs")),
            Suffix("為た", "為る", listOf("-た"), listOf("vs")),
            Suffix("きた", "くる", listOf("-た"), listOf("vk")),
            Suffix("来た", "来る", listOf("-た"), listOf("vk")),
            Suffix("來た", "來る", listOf("-た"), listOf("vk")),
            // rules 17 to 35: ...irregularVerbSuffixInflections('た', ['-た'], ['v5']), expanded
            Suffix("いった", "いく", listOf("-た"), listOf("v5")),
            Suffix("行った", "行く", listOf("-た"), listOf("v5")),
            Suffix("逝った", "逝く", listOf("-た"), listOf("v5")),
            Suffix("往った", "往く", listOf("-た"), listOf("v5")),
            Suffix("こうた", "こう", listOf("-た"), listOf("v5")),
            Suffix("とうた", "とう", listOf("-た"), listOf("v5")),
            Suffix("請うた", "請う", listOf("-た"), listOf("v5")),
            Suffix("乞うた", "乞う", listOf("-た"), listOf("v5")),
            Suffix("恋うた", "恋う", listOf("-た"), listOf("v5")),
            Suffix("問うた", "問う", listOf("-た"), listOf("v5")),
            Suffix("訪うた", "訪う", listOf("-た"), listOf("v5")),
            Suffix("宣うた", "宣う", listOf("-た"), listOf("v5")),
            Suffix("曰うた", "曰う", listOf("-た"), listOf("v5")),
            Suffix("給うた", "給う", listOf("-た"), listOf("v5")),
            Suffix("賜うた", "賜う", listOf("-た"), listOf("v5")),
            Suffix("揺蕩うた", "揺蕩う", listOf("-た"), listOf("v5")),
            Suffix("のたもうた", "のたまう", listOf("-た"), listOf("v5")),
            Suffix("たもうた", "たまう", listOf("-た"), listOf("v5")),
            Suffix("たゆとうた", "たゆたう", listOf("-た"), listOf("v5")),
            Suffix("ました", "ます", listOf("-た"), listOf("-ます")),
            Suffix("でした", "", listOf("-た"), listOf("-ません")),
            Suffix("かった", "", listOf("-た"), listOf("-ません", "-ん")),
        ),
    )

    private fun transform31(): Transform = Transform(
        key = "-ます",
        name = "-ます",
        rules = listOf(
            Suffix("ます", "る", listOf("-ます"), listOf("v1")),
            // rules 1 to 8: ...specialHonorificMasuInflections(['-ます'], ['v5d']), expanded
            WholeWord("いらっしゃいます", "いらっしゃる", listOf("-ます"), listOf("v5d")),
            WholeWord("ございます", "ござる", listOf("-ます"), listOf("v5d")),
            WholeWord("なさいます", "なさる", listOf("-ます"), listOf("v5d")),
            WholeWord("くださいます", "くださる", listOf("-ます"), listOf("v5d")),
            WholeWord("下さいます", "下さる", listOf("-ます"), listOf("v5d")),
            WholeWord("おっしゃいます", "おっしゃる", listOf("-ます"), listOf("v5d")),
            WholeWord("仰います", "仰る", listOf("-ます"), listOf("v5d")),
            WholeWord("仰有います", "仰有る", listOf("-ます"), listOf("v5d")),
            Suffix("います", "う", listOf("-ます"), listOf("v5d")),
            Suffix("ひます", "う", listOf("-ます"), listOf("v5d")),
            Suffix("きます", "く", listOf("-ます"), listOf("v5d")),
            Suffix("ぎます", "ぐ", listOf("-ます"), listOf("v5d")),
            Suffix("します", "す", listOf("-ます"), listOf("v5d", "v5s")),
            Suffix("ちます", "つ", listOf("-ます"), listOf("v5d")),
            Suffix("にます", "ぬ", listOf("-ます"), listOf("v5d")),
            Suffix("びます", "ぶ", listOf("-ます"), listOf("v5d")),
            Suffix("みます", "む", listOf("-ます"), listOf("v5d")),
            Suffix("ります", "る", listOf("-ます"), listOf("v5d")),
            Suffix("じます", "ずる", listOf("-ます"), listOf("vz")),
            Suffix("します", "する", listOf("-ます"), listOf("vs")),
            Suffix("為ます", "為る", listOf("-ます"), listOf("vs")),
            Suffix("きます", "くる", listOf("-ます"), listOf("vk")),
            Suffix("来ます", "来る", listOf("-ます"), listOf("vk")),
            Suffix("來ます", "來る", listOf("-ます"), listOf("vk")),
            Suffix("くあります", "い", listOf("-ます"), listOf("adj-i")),
        ),
    )

    private fun transform32(): Transform = Transform(
        key = "potential",
        name = "potential",
        rules = listOf(
            Suffix("れる", "る", listOf("v1"), listOf("v1", "v5d")),
            Suffix("える", "う", listOf("v1"), listOf("v5d")),
            Suffix("ける", "く", listOf("v1"), listOf("v5d")),
            Suffix("げる", "ぐ", listOf("v1"), listOf("v5d")),
            Suffix("せる", "す", listOf("v1"), listOf("v5d")),
            Suffix("てる", "つ", listOf("v1"), listOf("v5d")),
            Suffix("ねる", "ぬ", listOf("v1"), listOf("v5d")),
            Suffix("べる", "ぶ", listOf("v1"), listOf("v5d")),
            Suffix("める", "む", listOf("v1"), listOf("v5d")),
            Suffix("できる", "する", listOf("v1"), listOf("vs")),
            Suffix("出来る", "する", listOf("v1"), listOf("vs")),
            Suffix("これる", "くる", listOf("v1"), listOf("vk")),
            Suffix("来れる", "来る", listOf("v1"), listOf("vk")),
            Suffix("來れる", "來る", listOf("v1"), listOf("vk")),
        ),
    )

    private fun transform33(): Transform = Transform(
        key = "potential or passive",
        name = "potential or passive",
        rules = listOf(
            Suffix("られる", "る", listOf("v1"), listOf("v1")),
            Suffix("ざれる", "ずる", listOf("v1"), listOf("vz")),
            Suffix("ぜられる", "ずる", listOf("v1"), listOf("vz")),
            Suffix("せられる", "する", listOf("v1"), listOf("vs")),
            Suffix("為られる", "為る", listOf("v1"), listOf("vs")),
            Suffix("こられる", "くる", listOf("v1"), listOf("vk")),
            Suffix("来られる", "来る", listOf("v1"), listOf("vk")),
            Suffix("來られる", "來る", listOf("v1"), listOf("vk")),
        ),
    )

    private fun transform34(): Transform = Transform(
        key = "volitional",
        name = "volitional",
        rules = listOf(
            Suffix("よう", "る", emptyList(), listOf("v1")),
            Suffix("やう", "る", emptyList(), listOf("v1")),
            Suffix("おう", "う", emptyList(), listOf("v5")),
            Suffix("はう", "う", emptyList(), listOf("v5")),
            Suffix("こう", "く", emptyList(), listOf("v5")),
            Suffix("かう", "く", emptyList(), listOf("v5")),
            Suffix("ごう", "ぐ", emptyList(), listOf("v5")),
            Suffix("がう", "ぐ", emptyList(), listOf("v5")),
            Suffix("そう", "す", emptyList(), listOf("v5")),
            Suffix("さう", "す", emptyList(), listOf("v5")),
            Suffix("とう", "つ", emptyList(), listOf("v5")),
            Suffix("たう", "つ", emptyList(), listOf("v5")),
            Suffix("のう", "ぬ", emptyList(), listOf("v5")),
            Suffix("なう", "ぬ", emptyList(), listOf("v5")),
            Suffix("ぼう", "ぶ", emptyList(), listOf("v5")),
            Suffix("ばう", "ぶ", emptyList(), listOf("v5")),
            Suffix("もう", "む", emptyList(), listOf("v5")),
            Suffix("まう", "む", emptyList(), listOf("v5")),
            Suffix("ろう", "る", emptyList(), listOf("v5")),
            Suffix("らう", "る", emptyList(), listOf("v5")),
            Suffix("じよう", "ずる", emptyList(), listOf("vz")),
            Suffix("じやう", "ずる", emptyList(), listOf("vz")),
            Suffix("しよう", "する", emptyList(), listOf("vs")),
            Suffix("しやう", "する", emptyList(), listOf("vs")),
            Suffix("為よう", "為る", emptyList(), listOf("vs")),
            Suffix("為やう", "為る", emptyList(), listOf("vs")),
            Suffix("こよう", "くる", emptyList(), listOf("vk")),
            Suffix("こやう", "くる", emptyList(), listOf("vk")),
            Suffix("来よう", "来る", emptyList(), listOf("vk")),
            Suffix("来やう", "来る", emptyList(), listOf("vk")),
            Suffix("來よう", "來る", emptyList(), listOf("vk")),
            Suffix("來やう", "來る", emptyList(), listOf("vk")),
            Suffix("ましょう", "ます", emptyList(), listOf("-ます")),
            Suffix("ませう", "ます", emptyList(), listOf("-ます")),
            Suffix("かろう", "い", emptyList(), listOf("adj-i")),
            Suffix("からう", "い", emptyList(), listOf("adj-i")),
        ),
    )

    private fun transform35(): Transform = Transform(
        key = "volitional slang",
        name = "volitional slang",
        rules = listOf(
            Suffix("よっか", "る", emptyList(), listOf("v1")),
            Suffix("おっか", "う", emptyList(), listOf("v5")),
            Suffix("こっか", "く", emptyList(), listOf("v5")),
            Suffix("ごっか", "ぐ", emptyList(), listOf("v5")),
            Suffix("そっか", "す", emptyList(), listOf("v5")),
            Suffix("とっか", "つ", emptyList(), listOf("v5")),
            Suffix("のっか", "ぬ", emptyList(), listOf("v5")),
            Suffix("ぼっか", "ぶ", emptyList(), listOf("v5")),
            Suffix("もっか", "む", emptyList(), listOf("v5")),
            Suffix("ろっか", "る", emptyList(), listOf("v5")),
            Suffix("じよっか", "ずる", emptyList(), listOf("vz")),
            Suffix("しよっか", "する", emptyList(), listOf("vs")),
            Suffix("為よっか", "為る", emptyList(), listOf("vs")),
            Suffix("こよっか", "くる", emptyList(), listOf("vk")),
            Suffix("来よっか", "来る", emptyList(), listOf("vk")),
            Suffix("來よっか", "來る", emptyList(), listOf("vk")),
            Suffix("ましょっか", "ます", emptyList(), listOf("-ます")),
        ),
    )

    private fun transform36(): Transform = Transform(
        key = "-まい",
        name = "-まい",
        rules = listOf(
            Suffix("まい", "", emptyList(), listOf("v")),
            Suffix("まい", "る", emptyList(), listOf("v1")),
            Suffix("じまい", "ずる", emptyList(), listOf("vz")),
            Suffix("しまい", "する", emptyList(), listOf("vs")),
            Suffix("為まい", "為る", emptyList(), listOf("vs")),
            Suffix("こまい", "くる", emptyList(), listOf("vk")),
            Suffix("来まい", "来る", emptyList(), listOf("vk")),
            Suffix("來まい", "來る", emptyList(), listOf("vk")),
            Suffix("まい", "", emptyList(), listOf("-ます")),
        ),
    )

    private fun transform37(): Transform = Transform(
        key = "-おく",
        name = "-おく",
        rules = listOf(
            Suffix("ておく", "て", listOf("v5"), listOf("-て")),
            Suffix("でおく", "で", listOf("v5"), listOf("-て")),
            Suffix("とく", "て", listOf("v5"), listOf("-て")),
            Suffix("どく", "で", listOf("v5"), listOf("-て")),
            Suffix("ないでおく", "ない", listOf("v5"), listOf("adj-i")),
            Suffix("ないどく", "ない", listOf("v5"), listOf("adj-i")),
        ),
    )

    private fun transform38(): Transform = Transform(
        key = "-いる",
        name = "-いる",
        rules = listOf(
            Suffix("ている", "て", listOf("v1"), listOf("-て")),
            Suffix("てゐる", "て", listOf("v1"), listOf("-て")),
            Suffix("ておる", "て", listOf("v5"), listOf("-て")),
            Suffix("てる", "て", listOf("v1p"), listOf("-て")),
            Suffix("でいる", "で", listOf("v1"), listOf("-て")),
            Suffix("でゐる", "で", listOf("v1"), listOf("-て")),
            Suffix("でおる", "で", listOf("v5"), listOf("-て")),
            Suffix("でる", "で", listOf("v1p"), listOf("-て")),
            Suffix("とる", "て", listOf("v5"), listOf("-て")),
            Suffix("ないでいる", "ない", listOf("v1"), listOf("adj-i")),
            Suffix("ないでゐる", "ない", listOf("v1"), listOf("adj-i")),
        ),
    )

    private fun transform39(): Transform = Transform(
        key = "-ふ",
        name = "-ふ",
        rules = listOf(
            Suffix("ふ", "う", emptyList(), listOf("v5")),
        ),
    )

    private fun transform40(): Transform = Transform(
        key = "-き",
        name = "-き",
        rules = listOf(
            Suffix("き", "い", emptyList(), listOf("adj-i")),
        ),
    )

    private fun transform41(): Transform = Transform(
        key = "-げ",
        name = "-げ",
        rules = listOf(
            Suffix("げ", "い", emptyList(), listOf("adj-i")),
            Suffix("気", "い", emptyList(), listOf("adj-i")),
        ),
    )

    private fun transform42(): Transform = Transform(
        key = "-がる",
        name = "-がる",
        rules = listOf(
            Suffix("がる", "い", listOf("v5"), listOf("adj-i")),
        ),
    )

    private fun transform43(): Transform = Transform(
        key = "-やがる",
        name = "-やがる",
        rules = listOf(
            Suffix("やがる", "る", listOf("v5"), listOf("v1")),
            Suffix("いやがる", "う", listOf("v5"), listOf("v5")),
            Suffix("ひやがる", "う", listOf("v5"), listOf("v5")),
            Suffix("きやがる", "く", listOf("v5"), listOf("v5")),
            Suffix("ぎやがる", "ぐ", listOf("v5"), listOf("v5")),
            Suffix("しやがる", "す", listOf("v5"), listOf("v5")),
            Suffix("ちやがる", "つ", listOf("v5"), listOf("v5")),
            Suffix("にやがる", "ぬ", listOf("v5"), listOf("v5")),
            Suffix("びやがる", "ぶ", listOf("v5"), listOf("v5")),
            Suffix("みやがる", "む", listOf("v5"), listOf("v5")),
            Suffix("りやがる", "る", listOf("v5"), listOf("v5")),
            Suffix("じやがる", "ずる", listOf("v5"), listOf("vz")),
            Suffix("しやがる", "する", listOf("v5"), listOf("vs")),
            Suffix("為やがる", "為る", listOf("v5"), listOf("vs")),
            Suffix("きやがる", "くる", listOf("v5"), listOf("vk")),
            Suffix("来やがる", "来る", listOf("v5"), listOf("vk")),
            Suffix("來やがる", "來る", listOf("v5"), listOf("vk")),
        ),
    )

    private fun transform44(): Transform = Transform(
        key = "-え",
        name = "-え",
        rules = listOf(
            Suffix("ねえ", "ない", emptyList(), listOf("adj-i")),
            Suffix("めえ", "むい", emptyList(), listOf("adj-i")),
            Suffix("みい", "むい", emptyList(), listOf("adj-i")),
            Suffix("ちぇえ", "つい", emptyList(), listOf("adj-i")),
            Suffix("ちい", "つい", emptyList(), listOf("adj-i")),
            Suffix("せえ", "すい", emptyList(), listOf("adj-i")),
            Suffix("ええ", "いい", emptyList(), listOf("adj-i")),
            Suffix("ええ", "わい", emptyList(), listOf("adj-i")),
            Suffix("ええ", "よい", emptyList(), listOf("adj-i")),
            Suffix("いぇえ", "よい", emptyList(), listOf("adj-i")),
            Suffix("うぇえ", "わい", emptyList(), listOf("adj-i")),
            Suffix("けえ", "かい", emptyList(), listOf("adj-i")),
            Suffix("げえ", "がい", emptyList(), listOf("adj-i")),
            Suffix("げえ", "ごい", emptyList(), listOf("adj-i")),
            Suffix("せえ", "さい", emptyList(), listOf("adj-i")),
            Suffix("めえ", "まい", emptyList(), listOf("adj-i")),
            Suffix("ぜえ", "ずい", emptyList(), listOf("adj-i")),
            Suffix("っぜえ", "ずい", emptyList(), listOf("adj-i")),
            Suffix("れえ", "らい", emptyList(), listOf("adj-i")),
            Suffix("れえ", "らい", emptyList(), listOf("adj-i")),
            Suffix("ちぇえ", "ちゃい", emptyList(), listOf("adj-i")),
            Suffix("でえ", "どい", emptyList(), listOf("adj-i")),
            Suffix("れえ", "れい", emptyList(), listOf("adj-i")),
            Suffix("べえ", "ばい", emptyList(), listOf("adj-i")),
            Suffix("てえ", "たい", emptyList(), listOf("adj-i")),
            Suffix("ねぇ", "ない", emptyList(), listOf("adj-i")),
            Suffix("めぇ", "むい", emptyList(), listOf("adj-i")),
            Suffix("みぃ", "むい", emptyList(), listOf("adj-i")),
            Suffix("ちぃ", "つい", emptyList(), listOf("adj-i")),
            Suffix("せぇ", "すい", emptyList(), listOf("adj-i")),
            Suffix("けぇ", "かい", emptyList(), listOf("adj-i")),
            Suffix("げぇ", "がい", emptyList(), listOf("adj-i")),
            Suffix("げぇ", "ごい", emptyList(), listOf("adj-i")),
            Suffix("せぇ", "さい", emptyList(), listOf("adj-i")),
            Suffix("めぇ", "まい", emptyList(), listOf("adj-i")),
            Suffix("ぜぇ", "ずい", emptyList(), listOf("adj-i")),
            Suffix("っぜぇ", "ずい", emptyList(), listOf("adj-i")),
            Suffix("れぇ", "らい", emptyList(), listOf("adj-i")),
            Suffix("でぇ", "どい", emptyList(), listOf("adj-i")),
            Suffix("れぇ", "れい", emptyList(), listOf("adj-i")),
            Suffix("べぇ", "ばい", emptyList(), listOf("adj-i")),
            Suffix("てぇ", "たい", emptyList(), listOf("adj-i")),
        ),
    )

    private fun transform45(): Transform = Transform(
        key = "n-slang",
        name = "n-slang",
        rules = listOf(
            Suffix("んなさい", "りなさい", emptyList(), listOf("-なさい")),
            Suffix("らんない", "られない", listOf("adj-i"), listOf("adj-i")),
            Suffix("んない", "らない", listOf("adj-i"), listOf("adj-i")),
            Suffix("んなきゃ", "らなきゃ", emptyList(), listOf("-ゃ")),
            Suffix("んなきゃ", "れなきゃ", emptyList(), listOf("-ゃ")),
        ),
    )

    private fun transform46(): Transform = Transform(
        key = "imperative negative slang",
        name = "imperative negative slang",
        rules = listOf(
            Suffix("んな", "る", emptyList(), listOf("v")),
        ),
    )

    private fun transform47(): Transform = Transform(
        key = "kansai-ben negative",
        name = "kansai-ben",
        rules = listOf(
            Suffix("へん", "ない", emptyList(), listOf("adj-i")),
            Suffix("ひん", "ない", emptyList(), listOf("adj-i")),
            Suffix("せえへん", "しない", emptyList(), listOf("adj-i")),
            Suffix("へんかった", "なかった", listOf("-た"), listOf("-た")),
            Suffix("ひんかった", "なかった", listOf("-た"), listOf("-た")),
            Suffix("うてへん", "ってない", emptyList(), listOf("adj-i")),
        ),
    )

    private fun transform48(): Transform = Transform(
        key = "kansai-ben -て",
        name = "kansai-ben",
        rules = listOf(
            Suffix("うて", "って", listOf("-て"), listOf("-て")),
            Suffix("おうて", "あって", listOf("-て"), listOf("-て")),
            Suffix("こうて", "かって", listOf("-て"), listOf("-て")),
            Suffix("ごうて", "がって", listOf("-て"), listOf("-て")),
            Suffix("そうて", "さって", listOf("-て"), listOf("-て")),
            Suffix("ぞうて", "ざって", listOf("-て"), listOf("-て")),
            Suffix("とうて", "たって", listOf("-て"), listOf("-て")),
            Suffix("どうて", "だって", listOf("-て"), listOf("-て")),
            Suffix("のうて", "なって", listOf("-て"), listOf("-て")),
            Suffix("ほうて", "はって", listOf("-て"), listOf("-て")),
            Suffix("ぼうて", "ばって", listOf("-て"), listOf("-て")),
            Suffix("もうて", "まって", listOf("-て"), listOf("-て")),
            Suffix("ろうて", "らって", listOf("-て"), listOf("-て")),
            Suffix("ようて", "やって", listOf("-て"), listOf("-て")),
            Suffix("ゆうて", "いって", listOf("-て"), listOf("-て")),
        ),
    )

    private fun transform49(): Transform = Transform(
        key = "kansai-ben -た",
        name = "kansai-ben",
        rules = listOf(
            Suffix("うた", "った", listOf("-た"), listOf("-た")),
            Suffix("おうた", "あった", listOf("-た"), listOf("-た")),
            Suffix("こうた", "かった", listOf("-た"), listOf("-た")),
            Suffix("ごうた", "がった", listOf("-た"), listOf("-た")),
            Suffix("そうた", "さった", listOf("-た"), listOf("-た")),
            Suffix("ぞうた", "ざった", listOf("-た"), listOf("-た")),
            Suffix("とうた", "たった", listOf("-た"), listOf("-た")),
            Suffix("どうた", "だった", listOf("-た"), listOf("-た")),
            Suffix("のうた", "なった", listOf("-た"), listOf("-た")),
            Suffix("ほうた", "はった", listOf("-た"), listOf("-た")),
            Suffix("ぼうた", "ばった", listOf("-た"), listOf("-た")),
            Suffix("もうた", "まった", listOf("-た"), listOf("-た")),
            Suffix("ろうた", "らった", listOf("-た"), listOf("-た")),
            Suffix("ようた", "やった", listOf("-た"), listOf("-た")),
            Suffix("ゆうた", "いった", listOf("-た"), listOf("-た")),
        ),
    )

    private fun transform50(): Transform = Transform(
        key = "kansai-ben -たら",
        name = "kansai-ben",
        rules = listOf(
            Suffix("うたら", "ったら", emptyList(), emptyList()),
            Suffix("おうたら", "あったら", emptyList(), emptyList()),
            Suffix("こうたら", "かったら", emptyList(), emptyList()),
            Suffix("ごうたら", "がったら", emptyList(), emptyList()),
            Suffix("そうたら", "さったら", emptyList(), emptyList()),
            Suffix("ぞうたら", "ざったら", emptyList(), emptyList()),
            Suffix("とうたら", "たったら", emptyList(), emptyList()),
            Suffix("どうたら", "だったら", emptyList(), emptyList()),
            Suffix("のうたら", "なったら", emptyList(), emptyList()),
            Suffix("ほうたら", "はったら", emptyList(), emptyList()),
            Suffix("ぼうたら", "ばったら", emptyList(), emptyList()),
            Suffix("もうたら", "まったら", emptyList(), emptyList()),
            Suffix("ろうたら", "らったら", emptyList(), emptyList()),
            Suffix("ようたら", "やったら", emptyList(), emptyList()),
            Suffix("ゆうたら", "いったら", emptyList(), emptyList()),
        ),
    )

    private fun transform51(): Transform = Transform(
        key = "kansai-ben -たり",
        name = "kansai-ben",
        rules = listOf(
            Suffix("うたり", "ったり", emptyList(), emptyList()),
            Suffix("おうたり", "あったり", emptyList(), emptyList()),
            Suffix("こうたり", "かったり", emptyList(), emptyList()),
            Suffix("ごうたり", "がったり", emptyList(), emptyList()),
            Suffix("そうたり", "さったり", emptyList(), emptyList()),
            Suffix("ぞうたり", "ざったり", emptyList(), emptyList()),
            Suffix("とうたり", "たったり", emptyList(), emptyList()),
            Suffix("どうたり", "だったり", emptyList(), emptyList()),
            Suffix("のうたり", "なったり", emptyList(), emptyList()),
            Suffix("ほうたり", "はったり", emptyList(), emptyList()),
            Suffix("ぼうたり", "ばったり", emptyList(), emptyList()),
            Suffix("もうたり", "まったり", emptyList(), emptyList()),
            Suffix("ろうたり", "らったり", emptyList(), emptyList()),
            Suffix("ようたり", "やったり", emptyList(), emptyList()),
            Suffix("ゆうたり", "いったり", emptyList(), emptyList()),
        ),
    )

    private fun transform52(): Transform = Transform(
        key = "kansai-ben -く",
        name = "kansai-ben",
        rules = listOf(
            Suffix("う", "く", emptyList(), listOf("-く")),
            Suffix("こう", "かく", emptyList(), listOf("-く")),
            Suffix("ごう", "がく", emptyList(), listOf("-く")),
            Suffix("そう", "さく", emptyList(), listOf("-く")),
            Suffix("とう", "たく", emptyList(), listOf("-く")),
            Suffix("のう", "なく", emptyList(), listOf("-く")),
            Suffix("ぼう", "ばく", emptyList(), listOf("-く")),
            Suffix("もう", "まく", emptyList(), listOf("-く")),
            Suffix("ろう", "らく", emptyList(), listOf("-く")),
            Suffix("よう", "よく", emptyList(), listOf("-く")),
            Suffix("しゅう", "しく", emptyList(), listOf("-く")),
        ),
    )

    private fun transform53(): Transform = Transform(
        key = "kansai-ben adjective -て",
        name = "kansai-ben",
        rules = listOf(
            Suffix("うて", "くて", listOf("-て"), listOf("-て")),
            Suffix("こうて", "かくて", listOf("-て"), listOf("-て")),
            Suffix("ごうて", "がくて", listOf("-て"), listOf("-て")),
            Suffix("そうて", "さくて", listOf("-て"), listOf("-て")),
            Suffix("とうて", "たくて", listOf("-て"), listOf("-て")),
            Suffix("のうて", "なくて", listOf("-て"), listOf("-て")),
            Suffix("ぼうて", "ばくて", listOf("-て"), listOf("-て")),
            Suffix("もうて", "まくて", listOf("-て"), listOf("-て")),
            Suffix("ろうて", "らくて", listOf("-て"), listOf("-て")),
            Suffix("ようて", "よくて", listOf("-て"), listOf("-て")),
            Suffix("しゅうて", "しくて", listOf("-て"), listOf("-て")),
        ),
    )

    private fun transform54(): Transform = Transform(
        key = "kansai-ben adjective negative",
        name = "kansai-ben",
        rules = listOf(
            Suffix("うない", "くない", listOf("adj-i"), listOf("adj-i")),
            Suffix("こうない", "かくない", listOf("adj-i"), listOf("adj-i")),
            Suffix("ごうない", "がくない", listOf("adj-i"), listOf("adj-i")),
            Suffix("そうない", "さくない", listOf("adj-i"), listOf("adj-i")),
            Suffix("とうない", "たくない", listOf("adj-i"), listOf("adj-i")),
            Suffix("のうない", "なくない", listOf("adj-i"), listOf("adj-i")),
            Suffix("ぼうない", "ばくない", listOf("adj-i"), listOf("adj-i")),
            Suffix("もうない", "まくない", listOf("adj-i"), listOf("adj-i")),
            Suffix("ろうない", "らくない", listOf("adj-i"), listOf("adj-i")),
            Suffix("ようない", "よくない", listOf("adj-i"), listOf("adj-i")),
            Suffix("しゅうない", "しくない", listOf("adj-i"), listOf("adj-i")),
        ),
    )
}
