#!/usr/bin/env python3
"""Generate the per-language phrase fuse-exclusion asset.

The tokenizer's phrase re-glob (LatinEngine) fuses any n-gram whose form the
pack or an imported dictionary knows. Some pack phrase entries are pure
Wiktionary `&lit` cross-reference stubs ("Used other than figuratively or
idiomatically: see do, you.") — sequences Wiktionary itself marks as
non-idiomatic. Fusing those replaces real word tokens with a stub entry, so
they are excluded from fusing (lookup is unaffected: a typed query still
resolves them).

This script scans a built pack and (re)writes the `lit-only` section of
app/src/main/assets/phrase_nofuse/<lang>.txt, preserving every other section
(e.g. the LLM-adjudicated block) verbatim. File format: one lowercase phrase
per line; `#` lines are comments; the runtime loader ignores both.

Usage: gen_phrase_nofuse.py <pack dict.sqlite> <lang code> [assets dir]
"""
import sqlite3
import sys
from pathlib import Path

LIT_PREFIX = "Used other than figuratively or idiomatically"
BEGIN = "# --- lit-only stubs (generated by scripts/gen_phrase_nofuse.py; do not edit) ---"
END = "# --- end lit-only stubs ---"


def lit_only_phrases(db_path: str) -> list[str]:
    db = sqlite3.connect(db_path)
    # For each multi-word gate key (positions 0/2 — the fuse tier), collect
    # every gloss of every entry it can reach. Excludable only when ALL of
    # them are &lit stubs: a phrase with any real sense stays fusable here
    # and goes to the adjudication band instead.
    rows = db.execute(
        """
        SELECT h.text, s.glosses
        FROM headword h
        JOIN sense s ON s.entry_id = h.entry_id
        WHERE h.position IN (0, 2) AND h.text LIKE '% %'
        """
    )
    all_lit: dict[str, bool] = {}
    for text, glosses in rows:
        ok = all(
            g.startswith(LIT_PREFIX)
            for g in glosses.split("\t")
            if g.strip()
        )
        all_lit[text] = all_lit.get(text, True) and ok
    return sorted(t for t, lit in all_lit.items() if lit)


def rewrite(asset: Path, phrases: list[str]) -> None:
    lines = asset.read_text().splitlines() if asset.exists() else []
    # Drop the previous generated section (markers inclusive); keep the rest.
    kept: list[str] = []
    skipping = False
    for line in lines:
        if line == BEGIN:
            skipping = True
            continue
        if line == END:
            skipping = False
            continue
        if not skipping:
            kept.append(line)
    while kept and not kept[-1].strip():
        kept.pop()
    section = [BEGIN, *phrases, END]
    out = kept + ([""] if kept else []) + section + [""]
    asset.parent.mkdir(parents=True, exist_ok=True)
    asset.write_text("\n".join(out))


def main() -> None:
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    db_path, lang = sys.argv[1], sys.argv[2]
    assets = Path(sys.argv[3]) if len(sys.argv) > 3 else (
        Path(__file__).resolve().parent.parent / "app/src/main/assets/phrase_nofuse"
    )
    phrases = lit_only_phrases(db_path)
    asset = assets / f"{lang}.txt"
    rewrite(asset, phrases)
    print(f"{lang}: {len(phrases)} lit-only phrases -> {asset}")


if __name__ == "__main__":
    main()
